### ISSUE TITLE
Publisher not finding target profile in Reference.

### ISSUE THREAD

**Issue by nrdavis1** [HL7/fhir-ig-publisher#224]
The error message I'm seeing is this: Profile http://hl7.org/fhir/us/vitals/StructureDefinition/BPDevice is for type Device, which is not a Resource (which is required because the Observation.device element has type Reference).

**Comment by nrdavis1** [comment]
@markiantorno I have other errors just like this one; publisher can't use the target profile, even though I know it has the correct type and baseDefinition.  Also, I posted this error in Zulip in the Implementers stream under the topic of "Reference error not seen before".

**Comment by markiantorno** [comment]
Could you please provide the version of the publisher you are using, in addition to the data and command you executed to get this error. That way I can reproduce locally.

Thanks for filing an issue.

**Comment by markiantorno** [comment]
Also, I'm having issues finding the topic you referenced? Please tag me in the stream.

**Comment by nrdavis1** [comment]
Sorry, I mentioned the wrong stream.  It's the IG Creation stream.  You're tagged in this topic.  I'm using IG Publisher Version: v1.1.57

**Comment by grahamegrieve** [comment]
I think this is fixed now

**Comment by nrdavis1** [comment]
Sorry for not getting back to this for so long, I've been busy with my day job.  I'm now using the 1.1.76 version of the publisher (downloaded from the downloads page of the CI build) and I'm still seeing this error.

**Comment by nrdavis1** [comment]
To reproduce the error:  I'm running via command line,  java -jar <local copy of publisher> - ig ig.json 
IG can be found at https://github.com/HL7/cimi-vital-signs

**Comment by sirkyp** [comment]
@nrdavis1 - Did you ever find a solution to this? I am seeing a similar error as of today.

**Comment by nrdavis1** [comment]
@sirkyp - No.  I haven't had any time to follow up on it since I've been focuses solely on a different IG and my day job.  I'll have time after this week to get back to the issue.  Sorry that I don't have an answer for you.

**Comment by grahamegrieve** [comment]
where are you seeing the error?

**Comment by sirkyp** [comment]
@grahamegrieve - l saw it on a local IG I have been working on. I based it on a version of the 'sample-ig' from over a year ago. When I got back to it this week, I noticed the error ( and others ). My IG is pretty simple, so I pulled down the latest and greatest sample-ig and applied my changes to it, and the error went away. Sorry I don't have anything better to help on this one.s

**Comment by sirkyp** [comment]
@grahamegrieve @markiantorno - I am seeing this error again when working with Logical Models. If you want to see the problem, you can use the example FSH defined logical models found here:
http://build.fhir.org/ig/HL7/fhir-shorthand/branches/master/reference.html#defining-logical-models

It happens on this line (when one logical model references another logical model):
`* human 1..1 SU Reference(Human) "Family member" "A reference to the human family member"`

**Comment by nrdavis1** [comment]
Has there been any movement with this issue?  I'm still seeing the error running the latest version of the publisher.  Thanks!

**Comment by grahamegrieve** [comment]
This is an issue with the IG, not the IG publisher. But to prevent confusion in the future, I have added a new validation rule in the validator:

The structure definition constrains a kind of resource, but has a different kind (complex-type)

(on BPDevice)
